[package]
name = "dictcc"
version = "0.0.0"
authors = ["Mathias Lengler", "Kevin Deggelmann"]
license = "GPL-3.0"
description = "Rust API for use of dict.cc translation data."

[dependencies]
csv = "1.0.0-beta.5"
failure = "0.1.1"
env_logger = "0.4.3"
htmlescape = "0.3.1"
