[package]
name = "dictcc"
version = "0.0.0"
authors = ["Mathias Lengler", "Kevin Deggelmann"]
license = "GPL-3.0"
description = "Rust API for use of dict.cc translation data."

[dependencies]
csv = "1.0.0-beta.5"
failure = "0.1.1"
htmlescape = "0.3.1"
serde = "1"
serde_derive = "1"
nom = "3.2.1"
log = "0.4.0-rc.1"
env_logger = "0.5.0-rc.1"
